### PR TITLE
update the cluster-management-addon plugin to use latest MCH/MCE api

### PR DESCRIPTION
**Pull request by hanqiuzh**
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>

Tests:
- [x] can enable/disable managed-serviceaccount in MCE
- [x] can enable/disable managed-serviceaccount in MCH
- [x] can enable/disable search in MCH
- [x] can enable/disable cluster-proxy in MCH

### CODE REVIEW

**Comment by nathanweatherly** [comment]
Waiting for the completion of this user story: https://github.com/stolostron/backlog/issues/20010

**Comment by hanqiuzh** [comment]
/hold
will wait for the API change user story

**Comment by hanqiuzh** [comment]
/hold
hold again, the api changes are merged, and now it's different format (with overrides at top, will need to update again)

**Comment by hanqiuzh** [comment]
/unhold
updated

**Review by tphee — APPROVED** [review]

**Pull request merged**
