### PR TITLE
move the token & name to top level

### PR DESCRIPTION
**Pull request by hanqiuzh**
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>

fixes: https://github.com/stolostron/ocmplus.cm/issues/86

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
👍 kwargs for the win!

**Review by TheRealHaoLiu — APPROVED** [review]
/lgtm

**Comment by nathanweatherly** [comment]
Do tests need updated at the same time?

**Comment by hanqiuzh** [comment]
good catch, updated 👍

**Comment by tphee** [comment]
@hanqiuzh
- Could you update `cluster_proxy` plugin
- Could you update playbook https://github.com/stolostron/ocmplus.cm/blob/main/tests/integration/targets/multicluster_management/tasks/multicluster-management-playbook.yml

**Comment by hanqiuzh** [comment]
cluster_proxy is already top level ? @tphee , and tests is updated for managed_serviceaccount

**Comment by tphee** [comment]
@hanqiuzh nvm about cluster-proxy, can not use kwargs to a string

**Review by tphee — APPROVED** [review]

**Pull request merged**
