### PR TITLE
add option to configure name or generate_name for managed-serviceaccount

### PR DESCRIPTION
**Pull request by TheRealHaoLiu**
closes https://github.com/stolostron/ocmplus.cm/issues/87

### CODE REVIEW

**Comment by tphee** [comment]
@TheRealHaoLiu Could you update this playbook https://github.com/stolostron/ocmplus.cm/blob/main/tests/integration/targets/multicluster_management/tasks/multicluster-management-playbook.yml#L29-L36

**Comment by tphee** [comment]
@TheRealHaoLiu At the end of the playbook is missing the task to delete managed_serviceaccount:
```
    ocmplus.cm.managed_serviceaccount:
      state: absent
```

**Comment by TheRealHaoLiu** [comment]
updated PR per @tphee 's comment

**Review by hanqiuzh — APPROVED** [review]

**Review by tphee — APPROVED** [review]

**Pull request merged**
